name: devBuild

on:
  push:
   branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node_version: ${{ matrix.node-version }}
      - name: Run build
      - run: npm ci
      - run: npm build
