name: Build Dev
on:
  push:
    branches: [dev]

jobs:
  build_dev:
    runs-on: ubuntu-latest
    steps:
    - name: Setup reviewdog
      uses: reviewdog/action-setup@v1.0.0
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 12
    - run: npm ci
    - run: npm run prod_build
