name: Build Prod on merge request
on:
  pull_request:
    branches: [prod]

jobs:
  build_dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci
      - run: npm run prod_build
